repos:
    - repo: https://github.com/myint/autoflake
      rev: master
      hooks:
          - id: autoflake
    - repo: https://github.com/ambv/black
      rev: 19.10b0
      hooks:
          - id: black
            language_version: python3.7
    - repo: https://github.com/timothycrosley/isort
      rev: 5.2.0
      hooks:
          - id: isort
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.3
      hooks:
          - id: flake8
