[build-system]
requires = ["setuptools>=47.1.1", "setuptools_scm[toml]>=4.1.2", "wheel>=0.34.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "hmmer/_version.py"

[tool.isort]
profile = "black"
src_paths = ["hmmer"]
